"use client";

import Link from "next/link";
import { ArrowRight, Camera, ShieldAlert, Users } from "lucide-react";
import { PageShell } from "@/components/dashboard/page-shell";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useStats } from "@/hooks/api/use-stats";
import { useAlerts } from "@/hooks/api/use-alerts";
import { AlertsTrendChart } from "@/components/charts/alerts-trend";
import { StatusBadge } from "@/components/status-badge";
import { PageTransition } from "@/components/motion/page-transition";

function KpiCard({
  label,
  value,
  icon,
  hint,
}: {
  label: string;
  value: string;
  icon: React.ReactNode;
  hint: string;
}) {
  return (
    <Card className="glass rounded-2xl p-5">
      <div className="flex items-start justify-between gap-3">
        <div className="space-y-1">
          <div className="text-xs text-muted-foreground">{label}</div>
          <div className="text-2xl font-semibold tracking-tight">{value}</div>
        </div>
        <div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/15 ring-1 ring-primary/25">
          {icon}
        </div>
      </div>
      <div className="mt-3 text-xs text-muted-foreground">{hint}</div>
    </Card>
  );
}

export default function DashboardHomePage() {
  const stats = useStats();
  const alerts = useAlerts();

  return (
    <PageTransition>
      <PageShell
        title="Dashboard"
        description="KPIs, system health, and incident trends—updating in real time."
        actions={
          <Link href="/dashboard/alerts">
            <Button className="neon-ring bg-primary text-primary-foreground hover:bg-primary/90">
              Open Alerts <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </Link>
        }
      >
        {stats.isError ? (
          <Card className="glass rounded-2xl p-6">
            <div className="text-sm font-semibold">Failed to load stats</div>
            <div className="mt-1 text-sm text-muted-foreground">
              Please refresh—mock API may be temporarily unavailable.
            </div>
          </Card>
        ) : (
          <div className="grid gap-4 md:grid-cols-4">
            {stats.isLoading || !stats.data ? (
              Array.from({ length: 4 }).map((_, i) => (
                <Skeleton key={i} className="h-[126px] rounded-2xl bg-white/5" />
              ))
            ) : (
              <>
                <KpiCard
                  label="Total Students"
                  value={stats.data.totalStudents.toLocaleString()}
                  icon={<Users className="h-5 w-5 text-primary" />}
                  hint="Estimated active enrollment."
                />
                <KpiCard
                  label="Active Cameras"
                  value={stats.data.activeCameras.toLocaleString()}
                  icon={<Camera className="h-5 w-5 text-primary" />}
                  hint="Streaming and reachable."
                />
                <KpiCard
                  label="Security Alerts"
                  value={stats.data.securityAlerts.toLocaleString()}
                  icon={<ShieldAlert className="h-5 w-5 text-primary" />}
                  hint="Last 24 hours."
                />
                <KpiCard
                  label="System Status"
                  value={stats.data.systemStatus}
                  icon={<ShieldAlert className="h-5 w-5 text-primary" />}
                  hint="Overall health and latency."
                />
              </>
            )}
          </div>
        )}

        <div className="grid gap-4 lg:grid-cols-3">
          <Card className="glass rounded-2xl p-6 lg:col-span-2">
            <div className="flex items-start justify-between gap-4">
              <div className="space-y-1">
                <div className="text-sm font-semibold">Alerts & Access Trends</div>
                <div className="text-sm text-muted-foreground">
                  Live series generated by the mock `/api/stats`.
                </div>
              </div>
              <div className="text-xs text-muted-foreground">
                Refreshes every <span className="text-foreground">5s</span>
              </div>
            </div>
            <div className="mt-4">
              {stats.isLoading || !stats.data ? (
                <Skeleton className="h-[320px] rounded-2xl bg-white/5" />
              ) : (
                <AlertsTrendChart stats={stats.data} />
              )}
            </div>
          </Card>

          <Card className="glass rounded-2xl p-6">
            <div className="flex items-start justify-between gap-4">
              <div className="space-y-1">
                <div className="text-sm font-semibold">Latest Alerts</div>
                <div className="text-sm text-muted-foreground">Refreshing every 3s.</div>
              </div>
              <Link className="text-xs text-primary hover:underline" href="/dashboard/alerts">
                View all
              </Link>
            </div>

            <div className="mt-4 grid gap-3">
              {alerts.isLoading ? (
                <>
                  <Skeleton className="h-16 rounded-2xl bg-white/5" />
                  <Skeleton className="h-16 rounded-2xl bg-white/5" />
                  <Skeleton className="h-16 rounded-2xl bg-white/5" />
                </>
              ) : alerts.isError ? (
                <div className="rounded-2xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
                  Failed to load alerts.
                </div>
              ) : (alerts.data ?? []).length === 0 ? (
                <div className="rounded-2xl border border-border/60 bg-white/5 px-4 py-3 text-sm text-muted-foreground">
                  No alerts right now. System is quiet.
                </div>
              ) : (
                (alerts.data ?? []).slice(0, 5).map((a) => (
                  <Link
                    key={a.id}
                    href="/dashboard/alerts"
                    className="glass rounded-2xl px-4 py-3 transition-colors hover:bg-white/[0.06]"
                  >
                    <div className="flex items-center justify-between gap-3">
                      <div className="truncate text-sm font-medium">{a.title}</div>
                      <StatusBadge severity={a.severity} />
                    </div>
                    <div className="mt-1 line-clamp-1 text-xs text-muted-foreground">
                      {a.location} • {a.source}
                    </div>
                  </Link>
                ))
              )}
            </div>
          </Card>
        </div>

        <div className="grid gap-4 lg:grid-cols-3">
          <Card className="glass rounded-2xl p-6 lg:col-span-2">
            <div className="flex items-start justify-between gap-4">
              <div className="space-y-1">
                <div className="text-sm font-semibold">Access Control Overview</div>
                <div className="text-sm text-muted-foreground">
                  Zone-level status visualization (mock).
                </div>
              </div>
              <div className="rounded-full border border-border/60 bg-white/5 px-3 py-1 text-xs text-muted-foreground">
                RBAC-ready
              </div>
            </div>
            <div className="mt-5 grid gap-3 md:grid-cols-2">
              {[
                { zone: "North Gate", status: "Active", pct: 92 },
                { zone: "Library", status: "Active", pct: 88 },
                { zone: "Engineering", status: "Warning", pct: 71 },
                { zone: "Dormitories", status: "Active", pct: 95 },
              ].map((z) => (
                <div key={z.zone} className="glass rounded-2xl p-4">
                  <div className="flex items-center justify-between gap-3">
                    <div className="text-sm font-medium">{z.zone}</div>
                    <StatusBadge
                      severity={z.status === "Warning" ? "warning" : "active"}
                    />
                  </div>
                  <div className="mt-3 h-2 w-full overflow-hidden rounded-full bg-white/5">
                    <div
                      className={[
                        "h-full rounded-full",
                        z.status === "Warning"
                          ? "bg-gradient-to-r from-amber-400/60 to-amber-300/40"
                          : "bg-gradient-to-r from-primary/60 to-cyan-400/45",
                      ].join(" ")}
                      style={{ width: `${z.pct}%` }}
                    />
                  </div>
                  <div className="mt-2 text-xs text-muted-foreground">
                    Access events validated: <span className="text-foreground">{z.pct}%</span>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          <Card className="glass rounded-2xl p-6">
            <div className="space-y-1">
              <div className="text-sm font-semibold">Operator Notes</div>
              <div className="text-sm text-muted-foreground">
                Quick actions and reminders.
              </div>
            </div>
            <div className="mt-4 grid gap-3 text-sm">
              {[
                { t: "Verify Engineering access anomalies", d: "Review door logs and camera angle." },
                { t: "Monitor Parking perimeter", d: "Increased after-hours movement." },
                { t: "Confirm sensor calibration", d: "Weekly check scheduled today." },
              ].map((n) => (
                <div key={n.t} className="glass rounded-2xl px-4 py-3">
                  <div className="font-medium">{n.t}</div>
                  <div className="mt-1 text-sm text-muted-foreground">{n.d}</div>
                </div>
              ))}
            </div>
          </Card>
        </div>
      </PageShell>
    </PageTransition>
  );
}

